parameters: ~

services:
    acme.product.catalog:
        class: Acme_Zygourator_Model_Catalog
        factory_class: Mage
        factory_method: getModel
        arguments: [acme_zygourator/catalog]


    acme.product.finder:
        class: Product\Finder
        arguments: [@acme.product.catalog]
